# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: 5
  username: root
  password:

mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  socket: /tmp/mysql.sock
  host: localhost

test:
  <<: *default
  <<: *mysql
  database: test
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

development:
  <<: *default
  <<: *mysql
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  charset: utf8mb4
  database: development


production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  database: production
  charset: unicode
