default: &default
  adapter: postgresql
  pool: 5
  charset: unicode

test:
  <<: *default
  username: <%= ENV['POSTGRES_USER'] || 'grit_share' %>
  database: <%= ENV['POSTGRES_DATABASE'] || 'test' %>

development:
  <<: *default
  username: grit_share
  password: grit_share
  database: development

production:
  <<: *default
  username: grit_share
  password: grit_share
  url: <%= ENV['DATABASE_URL'] %>
  database: production
